USE EMPRESA
GO

/* CHARINDEX */
-- RETORNA UM INTEIRO DE ACORDO COM UMA BUSCA EM UMA VARCHAR
-- CHARINDEX(O QUE?, ONDE?, A PARTIR DE)
-- A CONTAGEM COMEÇA EM 1

SELECT 
NOME,
CHARINDEX('A', NOME)
FROM ALUNO
GO
-- RETORNA A POSIÇÃO DA PRIMEIRA LETRA 'A' APARECE EM CADA NOME
-- NO CASO 'ANDRE' NA POSIÇÃO 1, PRIMEIRA POSIÇÃO
-- NO CASO 'RUI' NA POSIÇÃO 0, NÃO TEM LETRA 'A'

SELECT 
NOME,
CHARINDEX('A', NOME, 2) AS 'INDICE'
FROM ALUNO
GO
-- RETORNA A POSIÇÃO DA PRIMEIRA LETRA 'A' APARECE EM CADA NOME,
-- A PARTIR DA SEGUNDA POSIÇÃO
-- NO CASO 'ANDRE', RETORNA 0, NÃO TEM 'A'
-- NO CASO 'ANA', RETORNA 3, TEM A NA TERCEIRA POSIÇÃO
-- A FUNÇÃO CONTINUA CONTANDO AS POSIÇÕES ORIGINAIS.

/* CRIAÇÃO DA TABELA ONDE O ARQUIVO IMPORATADO IRÁ RESIDIR*/

CREATE TABLE LANCAMENTO_CONTABIL(
CONTA INT,
VALOR INT,
DEB_CRED CHAR(1)
)
GO

-- VERIFICANDO
SELECT * FROM LANCAMENTO_CONTABIL
GO

/* BULK INSERT - IMPORTAÇÃO DE ARQUIVOS */

BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\SPB_Data\github_bkp\SQL-Server\Arquivos_importacao\CONTAS.txt'
WITH(
FIRSTROW = 2,
DATAFILETYPE = 'char',
FIELDTERMINATOR = '\t',
ROWTERMINATOR = '\n'
)
GO
-- FIRSTROW = COMEÇA A APARTIR DE QUE LINHA OS DADOS? (PRIMEIRA LINHA É CABEÇALHO)
-- DATAFILETYPE = TIPO DE ARQUIVO (DADOS)
-- FIELDTERMINATOR = ONDE TERMINA CADA DADO
	-- '\t' = TAB (ASCII)
	-- EM OUTRA SITUAÇÃO PODERIA SER ';'
-- ROWTERMINATOR = ONDE TERMINA CADA REGISTRO
	-- '\n' = ENTER

SELECT * FROM LANCAMENTO_CONTABIL
GO
-- ULTIMOS REGISTROS NULOS
-- PODE DELETAR NO ARQUIVO ORIGINAL

DELETE FROM LANCAMENTO_CONTABIL
GO

-- DAR BULK DE NOVO

SELECT * FROM LANCAMENTO_CONTABIL
GO

-- VERIFICANDO OS CAMPOS
SP_HELP LANCAMENTO_CONTABIL
GO

/* DESAFIO DO SALDO */
/*
QUERY QUE TRAGA O NUMERO DA CONTA
SALDO DA CONTA - 
DEVEDOR OU CREDOR
*/

-- RESOLUÇÃO (EU)
ALTER TABLE LANCAMENTO_CONTABIL
ADD DEBITO INT,
CREDITO INT
GO
UPDATE LANCAMENTO_CONTABIL SET DEBITO = (VALOR*-1)
WHERE DEB_CRED = 'D'
GO
UPDATE LANCAMENTO_CONTABIL SET CREDITO = VALOR
WHERE DEB_CRED = 'C'
GO

SELECT * FROM LANCAMENTO_CONTABIL
ORDER BY CONTA
GO

SELECT
CONTA,
(SUM(DEBITO) + SUM(CREDITO)) AS DEBI_CRED
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
ORDER BY CONTA
GO

CREATE TABLE DEBITO_CREDITO(
CONTA INT,
VALOR INT,
DEBITO_OU_CREDITO CHAR(1)
)
GO

INSERT INTO DEBITO_CREDITO (CONTA, VALOR)
SELECT
CONTA,
(SUM(DEBITO) + SUM(CREDITO))
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
ORDER BY CONTA
GO

SELECT * FROM DEBITO_CREDITO
GO

UPDATE DEBITO_CREDITO SET DEBITO_OU_CREDITO = 'D'
WHERE VALOR < 0
GO
UPDATE DEBITO_CREDITO SET DEBITO_OU_CREDITO = 'C'
WHERE VALOR >= 0
GO

SELECT * FROM DEBITO_CREDITO
ORDER BY CONTA
GO

DROP TABLE DEBITO_CREDITO
GO

-- GABARITO
-- TECNICA DE "FLAGAR" COLUNAS
SELECT 
CONTA,
VALOR,
DEB_CRED,
CHARINDEX('D',DEB_CRED) AS DEBITO,
CHARINDEX('C',DEB_CRED) AS CREDITO,
(CHARINDEX('C',DEB_CRED)*2 -1)  AS MULTIPLICADOR
FROM LANCAMENTO_CONTABIL
GO

/*
CONTA	VALOR	DEB_CRED	DEBITO	CREDITO	MULTIPLICADOR
1	9584	D	1	0	-1
1	46545	D	1	0	-1
1	4654	D	1	0	-1
1	45646556	D	1	0	-1
1	46545	D	1	0	-1
1	9554	D	1	0	-1
1	478945	D	1	0	-1
1	9568	D	1	0	-1
1	5784	D	1	0	-1
1	48	D	1	0	-1
1	478946	D	1	0	-1
1	7156	D	1	0	-1
2	4111	D	1	0	-1
2	6456145	D	1	0	-1
2	46545	D	1	0	-1
2	47986465	D	1	0	-1
2	478945	D	1	0	-1
2	9568	D	1	0	-1
2	5784	D	1	0	-1
2	48	D	1	0	-1
...
*/

SELECT
CONTA,
SUM(VALOR*(CHARINDEX('C',DEB_CRED)*2 -1)) AS SALDO
FROM LANCAMENTO_CONTABIL
GROUP BY CONTA
ORDER BY CONTA
GO

/*
CONTA	SALDO
1	-84729627
2	-211283772
3	276029296
4	183831802
5	-40245078
6	44790349
11	302112
13	94169827
17	131540482
19	139399682
20	-93078940
25	-3266007
33	-7513982
*/