-- DATABASE E TABELAS, VER QUERY3
USE EMPRESA
GO

/* DATA */
-- FUNÇÕES PARA TRABALHAR COM DATAS

SELECT * FROM ALUNO
GO

/* DATEDIFF - CALCULA A DIFERENÇA ENTRE 2 DATAS*/

/*1 PASSO*/
-- FUNÇÃO GETDATE() TRAS DIA E HORA
-- RETORNA A DATA ATUAL DO SISTEMA (ANO-MES-DIA HORA-MIN-SEG.MILESIMO)
SELECT 
NOME, 
GETDATE() AS DIA_HORA 
FROM ALUNO
GO

/*2 PASSO*/
-- DATEDIFF (INTERVALO, DATA INICIO, DATA TERMINO) RETURN INT
-- INTERVALO, INDICA AO SISTEMA COM QUE PARAMETRO ESTOU TRABALHANDO (DIA, MES, ANO, SEMANA)
SELECT 
NOME, 
DATEDIFF(DAY,NASCIMENTO, GETDATE()) AS "IDADE_EM_DIAS"
FROM ALUNO
GO

/*3 PASSO - RETORNO EM INTEIRO + OPERAÇÃO MATEMATICA*/
-- AMBOS OS CALCULOS TEM QUE DAR O MESMO RESULTADO

SELECT 
NOME, 
(DATEDIFF(DAY,NASCIMENTO, GETDATE())/365) AS "IDADE"
FROM ALUNO
GO

SELECT 
NOME, 
(DATEDIFF(MONTH,NASCIMENTO, GETDATE())/12) AS "IDADE"
FROM ALUNO
GO

SELECT 
NOME, 
DATEDIFF(YEAR,NASCIMENTO, GETDATE()) AS "IDADE"
FROM ALUNO
GO
-- ESTE ULTIMO APRESENTA UM RESULTADO DIFERENTE DOS OUTROS,
-- PQ LEVA EM CONSIDERAÇÃO O ANO BISSEXTO

/* DATENAME - TRAZ O NOME DA PARTE DA DATA EM QUESTÃO */
/*O RETORNO DESSA FUNÇÃO É UM STRING*/

-- RETORNA O NOME DO MÊS
SELECT NOME, DATENAME(MONTH, NASCIMENTO) AS "MES"
FROM ALUNO
GO

-- RETORNAR O ANO
SELECT NOME, DATENAME(YEAR, NASCIMENTO) AS "MES"
FROM ALUNO
GO

-- RETORNA O DIA DA SEMANA
SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO) AS "MES"
FROM ALUNO
GO
-- RETORNA O DIA DA SEMANA DA DATA

/* DATEPART - RETORNA PARTE DA DATA */
/* FUNCIONA DE MANEIRA PARECIDA DO DATENAME */
/* POREM O RETORNO É UM (INT)EIRO */

SELECT NOME, DATEPART(MONTH, NASCIMENTO) AS "MES"
FROM ALUNO
GO

/* VARIAS FUNÇÕES */

SELECT
NOME,
DATEPART(MONTH, NASCIMENTO) AS "NUM_MÊS",
DATENAME(MONTH, NASCIMENTO) AS "MÊS"
FROM ALUNO
GO

/* DATEADD - RETORNA UMA DATA SOMADO A OUTRA DATA */
/*DATEADD (INTERVALO, INCREMENTO INT, DATA) RETORNO DATA*/
-- INTERVALO, INDICA AO SISTEMA COM QUE PARAMETRO ESTOU TRABALHANDO (DIA, MES, ANO, SEMANA)
-- INCREMENTO, COM BASE NO PARAMETRO DO INTERVALO, QUANTO DEVE SER SOMADO (INT)
-- DATA A SER INCREMENTADA
-- RESPOSTA É O CALCULO RETORNANDO UMA DATA 

SELECT
DATEADD(DAY,365,GETDATE()) AS "1ANO_ADIANTE"
GO
-- RETORNA A DATA ATUAL + 1 ANO (365 DIAS)

SELECT DATEADD(YEAR, 10, GETDATE()) AS "+10ANOS"
-- RETORNA A DATA ATUAL + 10 ANOS