/* ACESSANDO O BANCO DE DADOS */
USE EMPRESA
GO

/* PROCEDURES */

CREATE TABLE PESSOA(
IDPESSOA INT PRIMARY KEY IDENTETITY,
NOME VARCHAR(30) NOT NULL,
SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M','F')), --ENUM
NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE(
IDTELEFONE INT PRIMARY KEY IDENTETITY,
TIPO CHAR(3) NOT NULL CHECK(TIPO IN('CEL','COM')), --ENUM
NUMERO CHAR(10) NOT NULL,
ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE
ADD CONSTRANT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA 
VALUES
('ANTONIO','M','1981-02-13'),
('DANIEL','M','1985-03-18'),
('CLEIDE','F','1979-10-13')
GO

INSERT INTO TELEFONE
VALUES
('CEL','9879008',1),
('COM','8757909',1),
('CEL','9875890',2),
('CEL','9347689',2),
('COM','2998689',3),
('COM','2098978',2),
('CEL','9008679',3)
GO

/* CRIANDO A PROCEDURE */

/* PROCEDURES ESTÁTICAS, SEM PARAMETROS */

CREATE PROC SOMA -- ABREVIADA, OU PODE USAR TAMBÉM "CREATE PROCEDURE"
AS
SELECT 10 + 10 AS SOMA
GO

-- CHAMANDO A PROCEDURE

SOMA
GO
-- OU
EXEC SOMA
GO

/* PROCEDURES DINÂNIMCAS, COM PARAMETROS */

CRATE PROC CONTA @NUM1 INT, @NUM2 INT
AS
SELECT @NUM1 + @NUM2 AS RESULTADO
GO

-- VARIAVEIS
-- "@NOME_VARIAVEL" É UMA VARIAVEL LOCAL
-- "@@NOME_VARIAVEL" É UMA VARIAVEL GLOBAL


-- EXECUTANDO
EXEC CONTA 90, 78
GO

/* APAGANDO A PROCEDURE */

DROP PROC CONTA
GO

/* PROCEDURES EM TABELAS */

SELECT
P.NOME,
T.NUMERO
FROM PESSOA P
INNER JOIN TELEFONE T
ON P.IDPESSOA = T.ID_PESSOA
WHERE T.TIPO = 'CEL'
GO

-- TRAZER OS TELEFONES DE ACORDO COM O TIPO DE TELEFONE PASSADO */
CREATE PROC TELEFONES @TIPO CHAR(3)
AS
SELECT
P.NOME,
T.NUMERO
FROM PESSOA P
INNER JOIN TELEFONE T
ON P.IDPESSOA = T.ID_PESSOA
WHERE TIPO = @TIPO
GO

-- CHAMANDO A PROCEDURE
EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO