-- ACESSANDO O BANCO DE DADOS
USE EMPRESA
GO

/* ATRIBUINDO RESULTADOS A VARIAVEIS */

-- CRIANDO TABELA
CREATE TABLE CARROS(
CARRO VARCHAR(20),
FABRICANTE VARCHAR(30)
)
GO

-- INSERINDO VALORES NA TABELA
INSERT INTO CARROS 
VALUES
('KA','FORD'),
('FIESTA','FORD'),
('PRISMA','FORD'),
('CLIO','RENAULT'),
('SANDERO','RENAULT'),
('CHEVETE','CHEVROLET'),
('OMEGA','CHEVROLET'),
('PALIO','FIAT'),
('DOBLO','FIAT'),
('UNO','FIAT'),
('GOL','VOLKSWAGEN')
GO

-- VERIFICAR REGISTROS
SELECT * FROM CARROS
GO

-- ATRIBUIÇÃO DE RESULTADOS EM VARIAVEIS
DECLARE 
	@V_CONT_FORD INT, @V_CONT_FIAT INT
BEGIN
	/* METODO 1 */
	-- O SELECT PRECISA RETORNAR UMA SIMPLES COLUNA 
	-- E UM SO RESUTADO
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
		WHERE FABRICANTE = 'FORD')
	
	PRINT 'QTD FORD: ' + CAST(@V_CONT_FORD AS VARCHAR)

	/* METODO 2 */
	SELECT @V_CONT_FIAT = COUNT(*) FROM CARROS WHERE FABRICANTE = 'FIAT'

	PRINT 'QTD FIAT: ' + CONVERT(VARCHAR, @V_CONT_FIAT)
END
GO
-- NO 'SET' PARA ATRIBUIÇÃO DE VARIAVEL, 
-- PODEMOS ATRIBUIR O RESULTADO DE UMA CONSULTA.
-- NESTES CASOS A CONSULTA SELECT APARECE ENTRE PARENTESES ().