USE EMPRESA
GO

/* CHARINDEX */
-- RETORNA UM INTEIRO DE ACORDO COM UMA BUSCA EM UMA VARCHAR
-- CHARINDEX(O QUE?, ONDE?, A PARTIR DE)
-- A CONTAGEM COMEÇA EM 1

SELECT 
NOME,
CHARINDEX('A', NOME)
FROM ALUNO
GO
-- RETORNA A POSIÇÃO DA PRIMEIRA LETRA 'A' APARECE EM CADA NOME
-- NO CASO 'ANDRE' NA POSIÇÃO 1, PRIMEIRA POSIÇÃO
-- NO CASO 'RUI' NA POSIÇÃO 0, NÃO TEM LETRA 'A'

SELECT 
NOME,
CHARINDEX('A', NOME, 2) AS 'INDICE'
FROM ALUNO
GO
-- RETORNA A POSIÇÃO DA PRIMEIRA LETRA 'A' APARECE EM CADA NOME,
-- A PARTIR DA SEGUNDA POSIÇÃO
-- NO CASO 'ANDRE', RETORNA 0, NÃO TEM 'A'
-- NO CASO 'ANA', RETORNA 3, TEM A NA TERCEIRA POSIÇÃO
-- A FUNÇÃO CONTINUA CONTANDO AS POSIÇÕES ORIGINAIS.

/* CRIAÇÃO DA TABELA ONDE O ARQUIVO IMPORATADO IRÁ RESIDIR*/

CREATE TABLE LANCAMENTO_CONTABIL(
CONTA INT,
VALOR INT,
DEB_CRED CHAR(1)
)
GO

-- VERIFICANDO
SELECT * FROM LANCAMENTO_CONTABIL
GO

/* BULK INSERT - IMPORTAÇÃO DE ARQUIVOS */

BULK INSERT LANCAMENTO_CONTABIL
FROM 'C:\SPB_Data\github_bkp\SQL-Server\Arquivos_importacao\CONTAS.txt'
WITH(
FIRSTROW = 2,
DATAFILETYPE = 'char',
FIELDTERMINATOR = '\t',
ROWTERMINATOR = '\n'
)
GO
-- FIRSTROW = COMEÇA A APARTIR DE QUE LINHA OS DADOS? (PRIMEIRA LINHA É CABEÇALHO)
-- DATAFILETYPE = TIPO DE ARQUIVO (DADOS)
-- FIELDTERMINATOR = ONDE TERMINA CADA DADO
	-- '\t' = TAB (ASCII)
	-- EM OUTRA SITUAÇÃO PODERIA SER ';'
-- ROWTERMINATOR = ONDE TERMINA CADA REGISTRO
	-- '\n' = ENTER

SELECT * FROM LANCAMENTO_CONTABIL
GO
-- ULTIMOS REGISTROS NULOS
-- PODE DELETAR NO ARQUIVO ORIGINAL

DELETE FROM LANCAMENTO_CONTABIL
GO

-- DAR BULK DE NOVO

SELECT * FROM LANCAMENTO_CONTABIL
GO

-- VERIFICANDO OS CAMPOS
SP_HELP LANCAMENTO_CONTABIL
GO

/* DESAFIO DO SALDO */
/*
QUERY QUE TRAGA O NUMERO DA CONTA
SALDO DA CONTA - 
DEVEDOR OU CREDOR
*/