/*AULA 99*/
/* CONECTANDO A UM BANCO DE DADOS */

USE EMPRESA
GO

/* CRIAÇÃO DE TABELAS */

CREATE TABLE ALUNO(
IDALUNO INT PRIMARY KEY IDENTITY,
NOME VARCHAR(30) NOT NULL,
SEXO CHAR(1) NOT NULL,
NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(50) UNIQUE
)
GO
-- IDENTITY = AUTO_INCREMENT
-- pode ser escrito também "IDENTITY (1,1)" (inciar em 1, incrementar de 1 em 1)
-- IDENTITY = IDENTITY (1,1), forma resumida

/*ABREVIAÇÕES DE REGRAS NO DICIONARIO DE DADOS - SISTEMA*/
-- 'PK' é abreviação de "PRIMARY KEY"
-- 'FK' é abreviação de "FOERIGN"
-- 'UQ' é abreviação de "UNIQUE"
-- 'CK' é abreviação de "CHECK"

/*CONSTRAINTS*/
-- regras

ALTER TABLE ALUNO
ADD CONSTRAINT CK_SEXO
CHECK (SEXO IN ('M','F'))
GO
-- Verifica se dentro da coluna SEXO, os valores são 'M' ou 'F'
-- Uma especie de substituto para o ENUM no SQL-Server
-- "CK" é "CHECK"

/* 1 X 1 */

CREATE TABLE ENDERECO(
IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
BAIRRO VARCHAR(30) NOT NULL,
UF CHAR(2) NOT NULL
CHECK (UF IN ('RJ','SP','MG')),
ID_ALUNO INT UNIQUE
)
GO

/*CRIANDO A FK*/

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY (ID_ALUNO)
REFERENCES ALUNO(IDALUNO)
GO

/* COMANDO DE DESCRIÇÃO */

-- No MYSQL os comandos eram:
-- DESC, SHOW CREATE TABLE

-- No SQL-Server a descriação é atraves de PROCEDURES 
-- PROCEDURES Já criadas e armazenadas no sistema
-- "STORAGE PROCEDURES" - SP
SP_COLUMNS ALUNO
GO
-- SP_COLUMNS = DESC

SP_HELP ALUNO
GO
-- SP_HELP = SHOW CREATE TABLE
-- MAIS DETALHADO

/* INSERINDO DADOS */

-- INSERT TABELA ALUNO
INSERT INTO ALUNO 
VALUES 
('ANDRE','M','1981/12/09','ANDRE@IG.COM'), 
('ANA','F','1978/03/09','ANA@IG.COM'), 
('RUI','M','1951/07/09','RUI@IG.COM'), 
('JOÃO','M','2002/11/09','JOAO@IG.COM') 
GO
-- Na coluna PK, com IDENTITY, não preciso passar valor nenhum

-- VERIFICANDO
SELECT * FROM ALUNO
GO

/*AULA 100*/

-- INSERT TABELA ENDERECO
INSERT INTO ENDERECO 
VALUES
('FLAMENGO','RJ',1),
('MORUMBI','SP',2),
('CENTRO','MG',3),
('CENTRO','SP',4)
GO

/*CRIANDO A TABELA TELEFONES*/

-- RELACIONAMENTO 1 X N (SEM UNIQUE)
CREATE TABLE TELEFONE(
IDTELEFONE INT PRIMARY KEY IDENTITY,
TIPO CHAR(3) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
ID_ALUNO INT
)
GO

-- CONSTRAINTS TELEFONE
ALTER TABLE TELEFONE
ADD CONSTRAINT CK_TELEFONE
CHECK (TIPO IN ('RES', 'COM', 'CEL'))
GO

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY (ID_ALUNO)
REFERENCES ALUNO (IDALUNO)
GO

-- INSERINDO DADOS NA TABELA TELEFONE
INSERT INTO TELEFONE 
VALUES
('CEL','7899889',1),
('RES','4325444',1),
('COM','4354354',2),
('CEL','2344556',2)
GO

-- VERIFICANDO OS DADOS NAS TABELAS
SELECT * FROM ALUNO
GO
SELECT * FROM TELEFONE
GO
SELECT * FROM ENDERECO
GO

/*PEGANDO DATA ATUAL DO SISTEMA*/
SELECT GETDATE()
GO

/*CLAUSULA AMBIGUA*/

SELECT 
A.NOME, 
T.TIPO, 
T.NUMERO, 
E.BAIRRO, 
E.UF
FROM ALUNO A
INNER JOIN ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
INNER JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
GO

-- LEFT JOIN - PARA TRAZER TODOS OS ALUNOS, MESMO OS SEM TELEFONE
SELECT 
A.NOME, 
T.TIPO, 
T.NUMERO, 
E.BAIRRO, 
E.UF
FROM ALUNO A
INNER JOIN ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
LEFT JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
GO

/*IFNULL - ISNULL*/
-- LIDANDO COM VALORES NULOS
-- IFNULL MySQL = ISNULL SQL Server
SELECT 
A.NOME, 
ISNULL(T.TIPO, 'SEM') AS "TIPO", 
ISNULL(T.NUMERO, 'SEM_NUMERO') AS "NUMERO", 
E.BAIRRO, 
E.UF
FROM ALUNO A
INNER JOIN ENDERECO E
ON A.IDALUNO = E.ID_ALUNO
LEFT JOIN TELEFONE T
ON A.IDALUNO = T.ID_ALUNO
GO
-- ISNULL, USAR ASPAS SIMPLES DENTRO DELE