/* ACESSANDO O BANCO DE DADOS */
USE EMPRESA
GO

/* CRIANDO UMA PROCEDURE QUE HAJA COMO UMA REGRA DE NEGÓCIO */
-- ISSO É UTIL PARA ALIVIAR A PARTE DE CONTROLLER 
--(ÁREA DA PROGRAMAÇÃO, QUE USA LINGUAGENS DE PROGRAMAÇÃO)
-- NORMALMENTE HÁ ÁREA DE CONTROLLER É QUE LEVA AS REGRAS DE NEGÓCIO.

-- POREM CASO HAJA HÁ NECESSITE DE ALIVIAR A ÁREA DE CONTROLLER (SERVIDOR)
-- É POSSIVEL PASSAR REGRAS DE NEGÓCIO DIRETO PARA O BANCO DE DADOS (ÁREA DE MODEL)

-- O LADO NEGATIVO:
-- CASO HAJA A NECESSIDADE DE MIGRAR DE BANCO DE DADOS,
-- O PROCESSO SE TORNA MAIS PENOSO.
-- POIS SERÁ NECESSARIO REPROGRAMAR AS REGRAS PRO NOVO BANCO DE DADOS.

-- LADO POSITIVO:
-- ALIVIA A ÁREA DE CONTROLLER,
-- TORNA A MIGRAÇÃO DE LINGUAGEM DE PROGRAMAÇÃO MAIS FÁCIL.

/* ÁREAS */
-- ÁREA DE VISÃO - HTML
-- ÁREA DE CONTROLLER - LINGUAGENS DE PROGRAMAÇÃO (JAVA, PYTHON, C#,...)
-- ÁREA DE MODEL - BANCO DE DADOS

/*----------------------------------------------------------------------*/

/* CRIAÇÃO DE TABELAS */

CREATE TABLE PESSOA(
IDPESSOA INT PRIMARY KEY IDENTITY,
NOME VARCHAR(30) NOT NULL,
SEXO CHAR(1) NOT NULL CHECK(SEXO IN('M','F')), --ENUM
NASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE01(
IDTELEFONE INT PRIMARY KEY IDENTITY,
TIPO CHAR(3) NOT NULL CHECK(TIPO IN('CEL','COM')), --ENUM
NUMERO CHAR(10) NOT NULL,
ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE01
ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

/* PROCEDURE COMO REGRA DE NEGÓCIO */
-- CADASTRAR OS DADOS DE PESSOAS E SEU RESPECTIVO TELEFONES 
-- AO MESMO TEMPO NAS TABELAS

CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
DECLARE @FK INT
INSERT INTO PESSOA VALUES (@NOME, @SEXO, @NASCIMENTO) -- GERA UM ID
SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)
-- SELECT @@IDENTITY [RETORNA O ÚLTIMO IDENTITY INSERIDO NA SEÇÃO]
-- PODERIA COLOCAR APENAS 'SELECT @@IDENTITY')
INSERT INTO TELEFONE01 VALUES (@TIPO, @NUMERO, @FK)
GO

-- EXECUTANDO A PROCEDURE
EXEC CADASTRO 'JORGE', 'M', '1981-01-01', 'CEL', '987842561'
GO

-- VERIFICANDO SE AS TABELAS FORAM PRENCHIDAS
SELECT * FROM PESSOA
SELECT * FROM TELEFONE01
GO
-- OU
SELECT
PESSOA.*,
TELEFONE01.*
FROM PESSOA
INNER JOIN TELEFONE01
ON PESSOA.IDPESSOA = TELEFONE01.ID_PESSOA
GO