-- ACESSANDO O BANCO DE DADOS
USE EMPRESA
GO

/* LOOP - WHILE */
-- EXECUTA DETERMINADA AÇÃO ENQUANTO UMA EXPRESSÃO FOR VERDADEIRA.
-- LOOP NORMALMENTE UTILIZA CONTADORES, QUE SÃO VARIAVEIS DE CONTROLE,
-- QUE SERVEM COMO UM MECÂNISMO DE PARADA.

DECLARE
	@I INT = 1 -- CONTADOR
BEGIN
	WHILE (@I < 15)
	BEGIN
		PRINT 'VALOR DE @I = ' + CAST(@I AS VARCHAR)
		SET @I = @I + 1
	END
END
GO